#!/usr/bin/env node
/**
 * OpenClaw 邮件功能测试
 * 测试邮件发送、接收、解析等功能
 */

// 邮件配置（示例）
const EMAIL_CONFIG = {
  smtp: {
    host: 'smtp.example.com',
    port: 587,
    secure: false,
    auth: {
      user: 'test@example.com',
      pass: 'password'
    }
  },
  imap: {
    host: 'imap.example.com',
    port: 993,
    secure: true,
    auth: {
      user: 'test@example.com',
      pass: 'password'
    }
  }
};

// 邮件模板
const EMAIL_TEMPLATES = {
  welcome: {
    subject: 'Welcome to OpenClaw+',
    body: 'Hello! Welcome to OpenClaw+ digital employee system.',
    to: 'user@example.com'
  },
  report: {
    subject: 'Daily Report from OpenClaw+',
    body: 'This is your daily report generated by OpenClaw+ digital employee.',
    to: 'admin@example.com'
  },
  alert: {
    subject: 'Security Alert from OpenClaw+',
    body: 'A security event has been detected and requires your attention.',
    to: 'security@example.com'
  }
};

// 模拟邮件发送功能
function simulateSendEmail(template) {
  console.log(`\n[EMAIL] 发送邮件`);
  console.log(`  收件人: ${template.to}`);
  console.log(`  主题: ${template.subject}`);
  console.log(`  内容: ${template.body.substring(0, 50)}...`);
  
  // 模拟发送延迟
  const delay = Math.floor(Math.random() * 500) + 200;
  
  return new Promise((resolve) => {
    setTimeout(() => {
      const success = Math.random() > 0.1; // 90% 成功率
      if (success) {
        console.log(`  [SUCCESS] ✅ 邮件发送成功 (${delay}ms)`);
        resolve({ success: true, delay });
      } else {
        console.log(`  [FAIL] ❌ 邮件发送失败`);
        resolve({ success: false, error: 'SMTP connection timeout' });
      }
    }, delay);
  });
}

// 模拟邮件接收功能
function simulateReceiveEmail() {
  console.log(`\n[EMAIL] 检查新邮件`);
  
  const mockEmails = [
    {
      from: 'user@example.com',
      subject: 'Question about OpenClaw+',
      body: 'How do I configure the digital employee?',
      date: new Date().toISOString()
    },
    {
      from: 'admin@example.com',
      subject: 'System Update',
      body: 'Please update to the latest version.',
      date: new Date(Date.now() - 3600000).toISOString()
    }
  ];
  
  const emailCount = Math.floor(Math.random() * 3);
  const emails = mockEmails.slice(0, emailCount);
  
  console.log(`  [INFO] 收到 ${emails.length} 封新邮件`);
  
  emails.forEach((email, index) => {
    console.log(`  [${index + 1}] ${email.from}: ${email.subject}`);
  });
  
  return { success: true, emails };
}

// 邮件解析功能
function parseEmailContent(email) {
  console.log(`\n[PARSE] 解析邮件内容`);
  console.log(`  发件人: ${email.from}`);
  console.log(`  主题: ${email.subject}`);
  
  // 提取关键信息
  const keywords = email.body.match(/\b\w{4,}\b/g) || [];
  const uniqueKeywords = [...new Set(keywords)].slice(0, 5);
  
  console.log(`  关键词: ${uniqueKeywords.join(', ')}`);
  
  // 判断邮件类型
  let category = 'general';
  if (email.subject.toLowerCase().includes('question')) {
    category = 'support';
  } else if (email.subject.toLowerCase().includes('update')) {
    category = 'notification';
  } else if (email.subject.toLowerCase().includes('alert')) {
    category = 'security';
  }
  
  console.log(`  分类: ${category}`);
  
  return {
    from: email.from,
    subject: email.subject,
    category,
    keywords: uniqueKeywords,
    priority: category === 'security' ? 'high' : 'normal'
  };
}

// 运行邮件功能测试
async function runEmailTests() {
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  OpenClaw 邮件功能测试');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  const results = {
    send: [],
    receive: [],
    parse: []
  };
  
  // 测试 1: 邮件发送
  console.log('\n[TEST 1] 邮件发送功能测试');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  
  for (const [name, template] of Object.entries(EMAIL_TEMPLATES)) {
    console.log(`\n测试模板: ${name}`);
    const result = await simulateSendEmail(template);
    results.send.push({ template: name, ...result });
  }
  
  // 测试 2: 邮件接收
  console.log('\n\n[TEST 2] 邮件接收功能测试');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  
  const receiveResult = simulateReceiveEmail();
  results.receive.push(receiveResult);
  
  // 测试 3: 邮件解析
  console.log('\n\n[TEST 3] 邮件解析功能测试');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  
  if (receiveResult.emails && receiveResult.emails.length > 0) {
    for (const email of receiveResult.emails) {
      const parsed = parseEmailContent(email);
      results.parse.push(parsed);
    }
  } else {
    console.log('  [INFO] 没有新邮件需要解析');
  }
  
  // 生成测试报告
  console.log('\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  测试结果汇总');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  // 发送测试结果
  const sendSuccess = results.send.filter(r => r.success).length;
  const sendFail = results.send.filter(r => !r.success).length;
  console.log(`邮件发送: ${sendSuccess} 成功, ${sendFail} 失败`);
  
  // 接收测试结果
  const receiveSuccess = results.receive.filter(r => r.success).length;
  console.log(`邮件接收: ${receiveSuccess} 成功`);
  
  // 解析测试结果
  console.log(`邮件解析: ${results.parse.length} 封邮件已解析`);
  
  const totalTests = results.send.length + results.receive.length + results.parse.length;
  const totalSuccess = sendSuccess + receiveSuccess + results.parse.length;
  
  console.log(`\n总计: ${totalSuccess}/${totalTests} 测试通过`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  return results;
}

// 执行测试
console.log('[INFO] 开始邮件功能测试...\n');
console.log('[NOTE] 这是模拟测试，实际邮件功能需要配置真实的 SMTP/IMAP 服务器\n');

runEmailTests().then(results => {
  console.log('[INFO] 邮件功能测试完成');
}).catch(error => {
  console.log(`[ERROR] 测试执行失败: ${error}`);
});
